final List<String> racasDeCachorro = [
    'Raça',
    'Vira-Lata',
    'Akita',
    'Basenji',
    'Basset Hound',
    'Beagle',
    'Bichon Frisé',
    'Border Collie',
    'Boxer',
    'Bull Terrier',
    'Bulldog Inglês',
    'Chihuahua',
    'Cocker Spaniel',
    'Dachshund',
    'Dálmata',
    'Dogue Alemão',
    'Golden Retriever',
    'Husky Siberiano',
    'Labrador Retriever',
    'Mastiff',
    'Pastor Alemão',
    'Pinscher',
    'Pit Bull',
    'Poodle',
    'Pug',
    'Rhodesian Ridgeback',
    'Rottweiler',
    'Shar Pei',
    'Shih Tzu',
    'Weimaraner',
    'Yorkshire Terrier',
  ];

  final List<String> idades = [
    'Idade',
    '1 mês',
    '2 meses',
    '3 meses',
    '4 meses',
    '5 meses',
    '6 meses',
    '7 meses',
    '8 meses',
    '9 meses',
    '10 meses',
    '11 meses',
    '1 ano',
    '2 anos',
    '3 anos',
    '4 anos',
    '5 anos',
    '6 anos',
    '7 anos',
    '8 anos',
    '9 anos',
    '10 anos',
  ];
  final List<String> portes = [
    'Porte',
    'Pequeno',
    'Medio',
    'Grande',
  ];

  final List<String> racasDeGato = [
    'Raça',
    'Vira-Lata',
    'Abissínio',
    'Bengal',
    'Burmese',
    'Chartreux',
    'Devon Rex',
    'Exótico',
    'Himalaio',
    'Maine Coon',
    'Manx',
    'Munchkin',
    'Persa',
    'Ragdoll',
    'Scottish Fold',
    'Siamês',
    'Sphynx',
    'Tonquinês',
    
  ];

  final List<String> avesDeEstimacao = [
    'Raça',
    'Agapornis',
    'Calopsita',
    'Cacatua',
    'Canário',
    'Caturrita',
    'Papagaio',
    'Periquito',
    'Rosela',
  ];

  final List<String> sexoList = [
    'Sexo',
    'Macho',
    'Fêmea',
  ];

  final List<String> tipoList = [
    'Tipo',
    'Cachorro',
    'Gato',
    'Pássaro'
  ];